### ISSUE TITLE
Test Windows

### ISSUE THREAD

**Issue by io7m** [LWJGL/lwjgl3-osgi#3]
Verify that the bundles resolve and run on Windows x86/x86_64.

**Comment by Martin-Idel** [comment]
- Test on Windows 10, x86_64 architecture
- Test on Windows 7, x86 architecture
- OSGI Implementation: Equinox from Eclipse Mars IDE
- Packages org.lwjgl.lwjgl and org.lwjgl.opengl
---
Result: Plugin fails to load. Error output:
> org.osgi.framework.BundleException: Could not resolve module: myBundle [488]
>   Unresolved requirement: Require-Bundle: org.lwjgl.lwjgl
>     -> Bundle-SymbolicName: org.lwjgl.lwjgl; bundle-version="3.1.2"
>        org.lwjgl.lwjgl [490]
>          Unresolved requirement: Import-Package: sun.misc; resolution:="optional"
>          Unresolved requirement: Require-Capability: osgi.native; native.paths.0:List<String>="lwjgl32.dll,jemalloc32.dll"; native.paths.2:List<String>="liblwjgl.so,libjemalloc.so"; native.paths.1:List<String>="lwjgl.dll,jemalloc.dll"; native.paths.3:List<String>="liblwjgl.dylib,libjemalloc.dylib"; filter:="(|(&(osgi.native.osname~=Windows)(osgi.native.processor~=x86))(&(osgi.native.osname~=Windows)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=Linux)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=MacOSX)(osgi.native.processor~=x86-64)))"
> 
>         at org.eclipse.osgi.container.Module.start(Module.java:434)
>         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
>         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
>         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
>         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
>         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
>         at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
>         at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

--- 
Evaluation: The MANIFEST.MF contains "osname=Windows". According to the OSGI specification (core specification 6.0.0, pg 100-101) from osgi.org, the correct name would be "Windows 10" (similarly for other Windows). There is no alias "Windows". In order to target most Windows versions, the alias "Win32" can be used (excluding Windows Server 2008 and WindowsCE).

However, I could not verify that the name in the MANIFEST.MF must be the complete OS name and cannot be a partial name. If this was the case, the error would be on the side of equinox of course.

---
Proposed Fix: I rewrote the MANIFEST.MF in the above packages replacing "Windows" by "Win32" and everything worked fine. If you agree that this should be fixed, I can offer to make the change in all packages and propose a Pull Request if it helps.

**Comment by io7m** [comment]
> Proposed Fix: I rewrote the MANIFEST.MF in the above packages replacing "Windows" by "Win32" and everything worked fine. If you agree that this should be fixed, I can offer to make the change in all packages and propose a Pull Request if it helps.

I agree. I'd certainly appreciate a PR!

Thanks again for testing these. I don't have access to a usable Windows or OS X environment right now, so it's always good to get reports from those that do.

**Comment by io7m** [comment]
I think we can assume that this is sufficiently tested now. We'll add new problems in new tickets.

**Comment by Martin-Idel** [comment]
One last question for planning purposes: Do you know when the new version with the fix will be released on Maven Central?

**Comment by io7m** [comment]
I was thinking about this yesterday... For reasons of sanity, I'd like to keep the bundles' version numbers in lock step with the LWJGL libraries. This probably means that the fix will go out with the next LWJGL release.

@Spasi Any thoughts?

**Comment by Spasi** [comment]
Not sure if there's a decent alternative to waiting for `3.1.3`.

**Comment by io7m** [comment]
I'm not aware of one.

**Comment by Martin-Idel** [comment]
That's what I thought and I agree that this is probably the only decent way. Thanks for the quick response!
